server:
  port: 9090

eureka:
  instance:
    hostname: localhost


#spring:
#  application:
#    name: api-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: sample-service
#          uri: lb://sample-service
#          predicates:
#            - Path=/sample/**

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000" #use "*" to allow all origins.
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: sample-service
          uri: lb://sample-service
          predicates:
            - Path=/sample/**
